version: '3.1'

services:

  web:
    build: .
    volumes:
      - "./app:/src/app"
    ports:
      - "3000:3000"
    links:
      - "mongo"
      - "mongo-express"
      
  mongo:
    image: mongo
    restart: always
    ports:
          - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo123
      

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo123
      